Task/save questions automatic
Ral15/jp2_offline pull request #11
Opened 2017-04-04 02:01 UTC by adal347

#### What's this PR do?

Save the sections automatically.

#### Where should the reviewer start?

/controllers/section.js
/controllers/user.js

#### How should this be manually tested?

npm test ./test/get-sections-test.js
When you login and if seccion.db file doesn't exists. Ask the questions from server and then save it.

#### Any background context you want to provide?

Remember to use npm run lint to have a style code updated

This template was adapted ~retrived~ from [Quickleft/Sprint.ly](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/)

2017-04-04 03:20 UTC, Ral15 commented on express-app/controllers/question.js
> +    pregunta.opciones_pregunta.forEach(function (item) {
this need to be in camel case

2017-04-04 12:57 UTC, Ral15 commented on express-app/controllers/section.js
> +    if (!fs.existsSync(sectionsPath)) {
why do check if the file exists and not with camo functions?

2017-04-04 13:00 UTC, Ral15 commented on express-app/controllers/user.js
> +const Section = require('./section');
This is a bit confusing, the name looks like a model, you should change it to 
`sectionController`  to keep consistency in the name of the models and controllers.

2017-04-04 13:02 UTC, Ral15 commented on express-app/controllers/user.js
> +            Section.getQuestions(user, request, response);
you render that dashboard view and then ask for the sections? and in the sections controller you render again the dashboard view??

2017-04-04 13:07 UTC, Ral15 commented on express-app/controllers/section.js
> +      isOnline().then((online) => {
Why do you check if the user is online again? This is already handled at the user controller.

2017-04-04 13:11 UTC, Ral15 commented on test/get-sections-test.js
> +      if (estudiosButton) if (fs.existsSync(sectionsPath)) assert.isOk(true, 'test is ok');
why don't you use one `if` only?

2017-04-04 13:14 UTC, Ral15 requested changes
check the comments..

2017-04-04 13:32 UTC, adal347 commented on express-app/controllers/question.js
> +    pregunta.opciones_pregunta.forEach(function (item) {
I can't let this in camel case because is the name that I retrieved from API. If I put in camel case creates an error.

2017-04-04 13:37 UTC, Ral15 commented on express-app/controllers/question.js
> +    pregunta.opciones_pregunta.forEach(function (item) {
oh okei :) @adal347

2017-04-15 00:18 UTC, erikiado approved these changes

2017-04-16 16:45 UTC, merged