Task/borrar estudio
Ral15/jp2_offline pull request #12
Opened 2017-04-04 02:54 UTC by Ral15

#### What's this PR do?
This PR includes the US 9.
#### Where should the reviewer start?
at express-app/controllers/estudio.js at line 108 through 134.

#### How should this be manually tested?
Create an estudio and then attempt to delete it.

#### Any background context you want to provide?
The apiToken of the user is hardcoded at the tests, this will change once we can all have the same user for testing.

This template was adapted ~retrived~ from [Quickleft/Sprint.ly](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/)

2017-04-04 11:38 UTC, erikiado commented on .eslintignore
> +/express-app/node_modules/
haz el PR con develop, son muchos archivos para revisar

2017-04-04 14:32 UTC, adal347 commented on testDB/users.db
> +{"username":"eugenio","password":"erikiado123","apiToken":"082be9526329ebea51d69e11a50217d93f21545d","_id":"V6DEwzQASu52PWI8"}
I think you need to delete the TestDB when you finish your tests. 

And Don't forget to run lint.

2017-04-07 12:59 UTC, erikiado requested changes

2017-04-07 12:59 UTC, erikiado commented on config.js
>  };
Please specify these are the test_ credentials

2017-04-07 12:59 UTC, erikiado commented on express-app/routes/urls.json
> +	"apiUrl" : "http://junipero.erikiado.com/",
Does this work or is it beetter without the last /

2017-04-07 12:59 UTC, erikiado commented on test/deleteEstudio-test.js
> +        return client.click('.swal2-confirm');
Are all these awaits are needed?

2017-04-07 12:59 UTC, erikiado commented on testDB/users.db
> +{"username":"eugenio","password":"erikiado123","apiToken":"082be9526329ebea51d69e11a50217d93f21545d","_id":"V6DEwzQASu52PWI8"}
this and/or maybe add it to gitignore

2017-04-07 12:59 UTC, erikiado commented on test/deleteEstudio-test.js
> +      .setValue('#password', config.password)
Can't the login be before the tests?

2017-04-07 12:59 UTC, erikiado commented on test/deleteEstudio-test.js
> +        return client.isVisible('#delete-estudio-' + estudioId);
Are we not checking it is deleted from DB?

2017-04-08 23:24 UTC, Ral15 commented on test/deleteEstudio-test.js
> +        return client.click('.swal2-confirm');
yes @erikiado

2017-04-08 23:31 UTC, Ral15 commented on express-app/routes/urls.json
> +	"apiUrl" : "http://junipero.erikiado.com/",
This works fine, still I'm going to remove the /

2017-04-08 23:31 UTC, Ral15 commented on test/deleteEstudio-test.js
> +      .setValue('#password', config.password)
I was not able to place the login at the beforeEach()..

2017-04-08 23:32 UTC, Ral15 commented on config.js
>  };
👌

2017-04-08 23:32 UTC, Ral15 commented on testDB/users.db
> +{"username":"eugenio","password":"erikiado123","apiToken":"082be9526329ebea51d69e11a50217d93f21545d","_id":"V6DEwzQASu52PWI8"}
👌

2017-04-08 23:45 UTC, Ral15 commented on test/deleteEstudio-test.js
> +        return client.isVisible('#delete-estudio-' + estudioId);
We do not delete estudiso form the DB, we only change its status to 'Eliminado'. That is why I check into the section of 'Eliminados' at the user dashboard for the estudioId.

Do you think it is still necessary to check that in the DB?
@erikiado

2017-04-11 18:29 UTC, erikiado approved these changes

2017-04-11 18:34 UTC, merged