Task/encryption
Ral15/jp2_offline pull request #20
Opened 2017-04-25 22:43 UTC by adal347

#### What's this PR do?

Shows how to encrypt the data if the data needs to be encrypted.

#### Where should the reviewer start?

DATA_ENCRYPTION.md

#### How should this be manually tested?

Doing the steps of DATA_ENCRYPTION.md checking after a collection was saved, check the db files.

#### Any background context you want to provide?

This template was adapted ~retrived~ from [Quickleft/Sprint.ly](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/)

2017-04-26 00:09 UTC, Ral15 requested changes

2017-04-26 00:09 UTC, Ral15 commented on DATA_ENCRYPTION.md
> +  * At function createCollection you will see a new Datastore function, add the options:
maybe be more specific and add the # line where the change should happen.

2017-04-26 00:09 UTC, Ral15 commented on DATA_ENCRYPTION.md
> +        var encrypted = Crypto.AES.encrypt(doc, DBKey);
DBKey should be in config file, and also explain that step.

2017-04-26 04:56 UTC, erikiado commented
a fork of camo could be made in order to avoid making this step everytime 
@Ral15 has more experience with that maybe he can help

2017-04-27 01:48 UTC, erikiado approved these changes

2017-04-27 02:00 UTC, Ral15 approved these changes

2017-04-27 14:15 UTC, merged