Task/readme
Ral15/jp2_offline pull request #21
Opened 2017-04-25 22:46 UTC by adal347

#### What's this PR do?

Add Readme for the repository (For the documentation)

#### Where should the reviewer start?

Readme.md

#### How should this be manually tested?

Check the file Readme.md if it's ok.

#### Any background context you want to provide?

Check if there is more to add at this file.

This template was adapted ~retrived~ from [Quickleft/Sprint.ly](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/)

2017-04-25 23:28 UTC, Ral15 requested changes

2017-04-25 23:28 UTC, Ral15 commented on README.md
> +  ENV: 'Testing'
'testing'**

2017-04-25 23:28 UTC, Ral15 commented on README.md
> +  npm lint
i believe it is npm run lint :)

2017-04-25 23:28 UTC, Ral15 commented on README.md
> +  electron-packager . "San Juan Pablo II" --platform=win32 --arch=x64
will this work on any OS? or just in Windows?

2017-04-26 03:08 UTC, adal347 commented on README.md
> +  electron-packager . "San Juan Pablo II" --platform=win32 --arch=x64
Yes, but you need to install Wine. That's why I put the link to Electron packager for more information

2017-04-26 03:49 UTC, Ral15 approved these changes

2017-04-26 04:57 UTC, erikiado approved these changes

2017-04-26 14:34 UTC, merged