Task/test online
Ral15/jp2_offline pull request #6
Opened 2017-03-06 04:48 UTC by adal347

What's this PR do?

This is a example test running the application, also give a How to test for future testing.

Where should the reviewer start?

The reviewer can start from HOW TO TEST. Then you can view the folder Test

How should this be manually tested?

Make a deploy for the application.

Any background context you want to provide?

Any comments will be review at instant

This template was adapted ~retrived~ from [Quickleft/Sprint.ly](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/)

2017-03-07 05:30 UTC, erikiado requested changes

2017-03-07 05:30 UTC, erikiado commented on express-app/routes/urls.json
> +	"apiUrl" : "http://bloque-adal.c9users.io",
This should not be this URL, change it to a configuration file

2017-03-07 05:30 UTC, erikiado commented on express-app/views/partials/sidenav.hbs
> +        <li><a href="#"><i class="glyphicon glyphicon-log-out"></i> Log Out</a></li>
This doesn't do nothing or does it?

2017-03-07 05:30 UTC, erikiado commented on test/login.test.js
> +      path: '../jp2-win32-x64/jp2.exe'
this should also be in the config file

2017-03-07 05:30 UTC, erikiado commented on test/login.test.js
> +  });
maybe put this as a test boilerplate, but this doesn't test the login

2017-03-09 19:02 UTC, Ral15 approved these changes

2017-03-11 01:37 UTC, erikiado approved these changes

2017-03-12 22:40 UTC, merged