Task/models
Ral15/jp2_offline pull request #7
Opened 2017-03-15 14:33 UTC by adal347

#### What's this PR do?

The models for Estudio, Add the models of Estudio, Seccion, Subseccion, Pregunta, Opcion Respuesta, Respuesta.

#### Where should the reviewer start?

in express-app/models/estudio.js

#### Any background context you want to provide?

Check if is the correct way to create models

This template was adapted ~retrived~ from [Quickleft/Sprint.ly](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/)

2017-03-15 14:59 UTC, Ral15 commented
No puedes mergear directo a master, tiene que ser a develop

2017-03-15 18:54 UTC, Ral15 commented on express-app/models/estudio.js
> +        this.familia = Familia;
Attributes names should be in english. Also, you need to import User model or this won't work.

2017-03-15 18:55 UTC, Ral15 requested changes
Change attribute names to english.

2017-03-16 02:11 UTC, Ral15 requested changes
refer to the models of the app online.

2017-03-16 02:11 UTC, Ral15 commented on express-app/models/estudio.js
> +          choices : ['Aprobado', 'Rechazado', 'Borrador', 'Revisión', 'Eliminado']
choices should be stored in a const array.

2017-03-16 02:11 UTC, Ral15 commented on express-app/models/pregunta.js
> +var Document = require('camo').Document;
this should be removed.

2017-03-16 02:11 UTC, Ral15 commented on express-app/models/pregunta.js
> +    }
there should be a 'subseccion' attribute in the model.

2017-03-16 02:11 UTC, Ral15 commented on express-app/models/pregunta.js
> +        this.respuesta = Respuesta;
a 'pregunta' doesn't have a 'respuesta', look at the models from the app online.

2017-03-16 02:11 UTC, Ral15 commented on express-app/models/respuesta.js
> +          this.opcion = OpcionRespuesta
why do you need 'this.opcion'?

2017-03-16 02:11 UTC, Ral15 commented on express-app/models/respuesta.js
> +    }
you are missing pregunta and estudio attributes, please refer to the models created at app online.

2017-03-16 02:11 UTC, Ral15 commented on express-app/models/subseccion.js
> +        this.questions = [Pregunta];
please refger to the models created at the app online.

2017-03-17 14:57 UTC, Ral15 requested changes

2017-03-17 14:57 UTC, Ral15 commented on express-app/models/estudio.js
> +        this.capturista = Number;
is this attribute the id from the User model? Don't you think we need all the User model?

2017-03-17 14:57 UTC, Ral15 commented on express-app/models/seccion.js
> +        this.numero = Number;
what does this means?

2017-03-17 17:25 UTC, Ral15 requested changes

2017-03-17 17:25 UTC, Ral15 commented on express-app/models/pregunta.js
> +          default : 1
not sure if this should have a default value since "Pregunta" will be created only once per "Estudio" and the value will "never change".

2017-03-17 17:25 UTC, Ral15 commented on express-app/models/pregunta.js
> +          default : 1
same for this one.

2017-03-17 20:36 UTC, adal347 commented on express-app/models/pregunta.js
> +          default : 1
I let a Default in Id. If something we're wrong when app offline retrived the data from the app online we can see it. I put 0 as default to see it.

2017-03-17 20:36 UTC, adal347 commented on express-app/models/pregunta.js
> +          default : 1
Same as before

2017-03-17 20:38 UTC, Ral15 approved these changes
:call_me_hand:

2017-03-17 20:39 UTC, merged