Task/create estudio
Ral15/jp2_offline pull request #8
Opened 2017-03-20 21:11 UTC by Ral15

#### What's this PR do?
This PR creates a 'Estudio', there is a button at user's dashboard with the label: "Crear estudio", when clicked it sends the user to a form that accepts the address of the Family, when submitted the Estudio is created at local db.

#### Where should the reviewer start?
The main logic is at controllers/estudio.js

#### How should this be manually tested?
Follow the flow of the task.

#### Any background context you want to provide?
There are no tests(yet) for this PR jeje 

This template was adapted ~stolen~ from [Quickleft/Sprint.ly](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/)

2017-03-21 22:17 UTC, adael2 commented on express-app/controllers/estudio.js
> +      console.log(editedEstudio);
It necesary leave this console log. Or you can delete it??

2017-03-21 22:17 UTC, adael2 commented on express-app/controllers/estudio.js
> +    console.log(request.params.id);
Same for this one

2017-03-21 22:17 UTC, adael2 commented on express-app/controllers/family.js
> +    // console.log(data);
Same for this

2017-03-21 22:17 UTC, adael2 commented on express-app/controllers/family.js
> +    // console.log(newData);
Same for this

2017-03-21 22:17 UTC, adal347 commented on express-app/controllers/family.js
> +  * This function checks if user exists in database, if there is
I think that you copy the comments of "/controllers/user.js"?

2017-03-21 22:17 UTC, adal347 commented on express-app/controllers/family.js
> +      spei: 10
What is this field? I don't remember and I can't find in detalle MER document

2017-03-21 22:17 UTC, adal347 commented on express-app/models/comentario.js
> + * family : FR Family
What is this FR? is not in the model, you need in the model or is only a embedded document

2017-03-21 22:17 UTC, adal347 commented on express-app/models/estudiante.js
> +    this.spei = Number;
Same as 'controller/family.js'

2017-03-24 03:07 UTC, erikiado requested changes

2017-03-24 03:07 UTC, erikiado commented on express-app/app.js
The order of the imports should be:
Default Libraries
Third Parties Libs
Project Libs

2017-03-24 03:07 UTC, erikiado commented on express-app/app.js
> +  secret: 'keyboard cat',
Config file

2017-03-24 03:07 UTC, erikiado commented on express-app/controllers/estudio.js
> +      response.render('family');
doesn't this give an error?
or better send a 404

2017-03-24 03:07 UTC, erikiado commented on express-app/controllers/estudio.js
> +    let family = familyController.createFamily(data);
Start using await for this type of tasks

2017-03-24 03:07 UTC, erikiado commented on express-app/controllers/estudio.js
> +  },
family
.then((newFamily) => {
  //create estudio
  let estudio = Estudio.create({
    tokenCapturista: token,
    familia: newFamily
  });
  //save estudio
  return estudio.save();
}).then((newEstudio) => {
    response.render('members', {
      userToken: token, 
      estudioId: newEstudio._id, 
      family: newFamily
    });      
  })
.catch((err) => {
  //family could not be created
  console.log(err);
})
},

2017-03-24 03:07 UTC, erikiado commented on express-app/controllers/estudio.js
> +    .catch((e) => {
promise

2017-03-24 03:07 UTC, erikiado commented on express-app/app.js
> +hbs.registerHelper('ifCond', function(v1, v2, opt) {
I think this should be renamed to something more descriptive like ifEquals

2017-03-24 03:07 UTC, erikiado commented on express-app/controllers/estudio.js
> +    const data = request.body;
When is this data validated or sanitized?

2017-03-24 03:07 UTC, erikiado commented on express-app/controllers/family.js
> +  createMembers: function (request, response) {
Why are some controllers receiving both request and response, instead of some data like the ones above `editFamily: function(data, id)`

2017-03-24 03:07 UTC, erikiado commented on express-app/controllers/family.js
> +  },
In ` createFamily: function(data)` the family is saved and that promise is what is returned, in this case I'm not sure  you are creating correctly the member or tutor

2017-03-24 03:07 UTC, erikiado commented on express-app/models/estudio.js
> +    this.status = {
Spanglish

2017-03-24 03:07 UTC, erikiado commented on express-app/models/familia.js
> +  'Soltero',
Are this going to stay here or are they suppose to be pulled from the server?

2017-03-24 03:07 UTC, erikiado commented on express-app/models/miembro.js
> +      type: Date,
This should be a Number

2017-03-24 03:07 UTC, erikiado commented on express-app/models/opcion_respuesta.js
> +    return 'opcion_respuesta';
Maybe you could use the convention you were using

2017-03-24 03:07 UTC, erikiado commented on express-app/models/periodo.js
> +    this.periocidad = {
this word doesn't exist maybe you were looking for periodicidad

2017-03-24 03:07 UTC, erikiado commented on express-app/models/pregunta.js
> +    this.opcionesPregunta = [OpcionRespuesta];
Is this refering to the Opciones de Respuesta?

2017-03-24 03:07 UTC, erikiado commented on express-app/models/tutor.js
> +  "madre",
Are this going to be displayed as options?
In that case it is better to use upper case

2017-03-24 03:07 UTC, erikiado commented on express-app/views/members.hbs
> +      <script src="/jquery/jquery.js"></script>
Reused code, make a partial

2017-03-28 05:17 UTC, Ral15 commented on express-app/controllers/estudio.js
> +      response.render('family');
No, what this does is render the family view without information of a previously created Estudio.  At line 17 is an IF condition that checks if there is an ID at the query url.

Maybe I wasn't clear with the documentation of this function, do you need me to be more specific?

@erikiado

2017-03-28 05:18 UTC, Ral15 commented on express-app/controllers/estudio.js
> +    const data = request.body;
no, all validation occurs at front, do you think is still necessary to sanitize data? @erikiado

2017-03-29 01:08 UTC, Ral15 commented on express-app/models/familia.js
> +  'Soltero',
This are not pulled from the endpoint, at least not right now...

2017-03-30 18:08 UTC, Ral15 reviewed
changes done

2017-04-01 01:46 UTC, adael2 requested changes

2017-04-01 01:46 UTC, adael2 commented on express-app/app.js
> +hbs.registerHelper('ifEq', function(v1, v2, opt) {
What is v1 and v2?

2017-04-01 01:46 UTC, adal347 commented on express-app/views/members.hbs
> +                  <button type="submit">dale</button>
I think that the button could have another value

2017-04-01 01:46 UTC, adal347 commented on express-app/models/estudio.js
> +      default: opcionesStatusChoices[0],
opcionesStatusChoices[0] is equal to "Aprobado", "Borrador" is the option 3 so this line would be opcionesStatusChoices[2]

2017-04-01 01:46 UTC, adal347 commented on express-app/routes/urls.json
> +	"memberCreate": "/family/member/create/"
In the .hbs you send the studio id. So when you add a member the url doesn't match with this one so sends this message "Cannot POST /estudio/member/create/"

2017-04-01 01:46 UTC, adal347 commented on express-app/routes/urls.json
> +	"member": "/estuido/member/",
your url said "/estuido" this need to be "/estudio", right??

2017-04-01 03:05 UTC, Ral15 commented on express-app/app.js
> +hbs.registerHelper('ifEq', function(v1, v2, opt) {
value1, value 2

2017-04-01 03:05 UTC, Ral15 commented on express-app/views/members.hbs
> +                  <button type="submit">dale</button>
yep you're right, mb

2017-04-01 04:09 UTC, erikiado approved these changes

2017-04-01 05:14 UTC, merged